service: lambda-test # NOTE: update this with your service name
provider:
  name: aws
  runtime: nodejs8.10
functions:
  hello:
    handler: handler.hello
    events:
     - http:
         path: /${self:service}
         method: get
  getUser:
    handler: handler.getUser
    events:
     - http:
         path: /${self:service}/getUser
         method: get
  printStream:
    handler: handler.printStream
    name: test-stream-name
    description: this is a test of consuming kinesis stream
    events:
      - stream:
        arn: arn:aws:kinesis:us-east-1:#{AWS::AccountId}:stream/testStream
        batchSize: 10
        startingPosition: LATEST
        enabled: true
plugins:
  - serverless-offline
